/**
 * Sync design tokens from design-system/tokens/*.json → src/styles/tokens.generated.css
 *
 * Usage:
 *   npm run sync-tokens         (generate/overwrite tokens.generated.css)
 *   npm run sync-tokens:check   (detect drift, exit 1 if out of sync)
 */

import * as fs from "node:fs";
import * as path from "node:path";

const ROOT = path.resolve(__dirname, "..");
const COLORS_PATH = path.join(ROOT, "design-system/tokens/colors.json");
const MISC_PATH = path.join(ROOT, "design-system/tokens/misc.json");
const OUTPUT_PATH = path.join(ROOT, "src/styles/tokens.generated.css");

// ── Types ────────────────────────────────────────────────────────────────────

type Palette = Record<string, string | Record<string, string>>;
type SemanticEntry = { light: string; dark: string };
type ColorsJson = { palette: Palette; semantic: Record<string, SemanticEntry> };
type MiscJson = {
  radius?: {
    base?: string;
    /** Tailwind radius scale — Figma 라이브러리 truth와 동기화 */
    scale?: Record<string, number | string>;
  };
};

// ── HSL conversion ───────────────────────────────────────────────────────────

function hexToHsl(hex: string): { h: number; s: number; l: number } {
  const m = hex.match(/^#([0-9a-fA-F]{6})$/);
  if (!m) throw new Error(`Invalid hex color: ${hex}`);
  const int = parseInt(m[1], 16);
  const r = ((int >> 16) & 255) / 255;
  const g = ((int >> 8) & 255) / 255;
  const b = (int & 255) / 255;

  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;

  let h = 0;
  let s = 0;
  if (max !== min) {
    const d = max - min;
    s = d / (1 - Math.abs(2 * l - 1));
    if (max === r) h = ((g - b) / d + (g < b ? 6 : 0)) * 60;
    else if (max === g) h = ((b - r) / d + 2) * 60;
    else h = ((r - g) / d + 4) * 60;
  }
  return { h, s, l };
}

function formatHsl(
  { h, s, l }: { h: number; s: number; l: number },
  alpha = 1,
): string {
  const hRound = Math.round(h);
  const sPct = Math.round(s * 1000) / 10;
  const lPct = Math.round(l * 1000) / 10;
  const trim = (n: number) => {
    const str = n.toString();
    return str.endsWith(".0") ? str.slice(0, -2) : str;
  };
  const base = `${hRound} ${trim(sPct)}% ${trim(lPct)}%`;
  if (alpha >= 1) return base;
  return `${base} / ${alpha}`;
}

// ── Palette alias resolution ─────────────────────────────────────────────────

/**
 * Parse an alias string with optional alpha suffix.
 *   "palette/neutral/950"     → { path: "palette/neutral/950", alpha: 1 }
 *   "palette/black@0.3"       → { path: "palette/black",       alpha: 0.3 }
 */
function parseAlias(ref: string): { path: string; alpha: number } {
  const [path, alphaStr] = ref.split("@");
  const alpha = alphaStr === undefined ? 1 : parseFloat(alphaStr);
  if (Number.isNaN(alpha) || alpha < 0 || alpha > 1) {
    throw new Error(`Invalid alpha in alias: ${ref}`);
  }
  return { path, alpha };
}

function resolveAlias(ref: string, palette: Palette): { hex: string; alpha: number } {
  const { path, alpha } = parseAlias(ref);
  // "palette/neutral/950" → palette.neutral["950"]
  // "palette/white"       → palette.white
  const parts = path.split("/");
  if (parts[0] !== "palette") {
    throw new Error(`Unsupported alias namespace: ${ref}`);
  }
  let current: unknown = palette;
  for (let i = 1; i < parts.length; i++) {
    if (typeof current !== "object" || current === null) {
      throw new Error(`Cannot resolve alias ${ref}: ${parts.slice(0, i).join("/")} is not an object`);
    }
    current = (current as Record<string, unknown>)[parts[i]];
    if (current === undefined) {
      throw new Error(`Alias not found: ${ref}`);
    }
  }
  if (typeof current !== "string") {
    throw new Error(`Alias ${ref} does not resolve to a hex string`);
  }
  return { hex: current, alpha };
}

// ── Generator ────────────────────────────────────────────────────────────────

function generateCss(colors: ColorsJson, misc: MiscJson): string {
  const { palette, semantic } = colors;
  const semanticNames = Object.keys(semantic);

  const lines: string[] = [];
  lines.push("/* AUTO-GENERATED by scripts/sync-tokens.ts — DO NOT EDIT */");
  lines.push("/* Run `npm run sync-tokens` to regenerate from design-system/tokens/*.json */");
  lines.push("");

  // :root
  lines.push(":root {");
  for (const name of semanticNames) {
    const { hex, alpha } = resolveAlias(semantic[name].light, palette);
    const hsl = formatHsl(hexToHsl(hex), alpha);
    lines.push(`  --${name}: ${hsl};`);
  }
  if (misc.radius?.base) {
    lines.push("");
    lines.push(`  --radius: ${misc.radius.base};`);
  }
  lines.push("}");
  lines.push("");

  // .dark
  lines.push(".dark {");
  for (const name of semanticNames) {
    const { hex, alpha } = resolveAlias(semantic[name].dark, palette);
    const hsl = formatHsl(hexToHsl(hex), alpha);
    lines.push(`  --${name}: ${hsl};`);
  }
  lines.push("}");
  lines.push("");

  // @theme inline
  lines.push("@theme inline {");
  lines.push("  /* Semantic color tokens (Tailwind v4 utility mapping) */");
  for (const name of semanticNames) {
    lines.push(`  --color-${name}: hsl(var(--${name}));`);
  }
  lines.push("");
  lines.push("  /* Palette (raw hex) */");
  for (const [paletteName, value] of Object.entries(palette)) {
    if (typeof value === "string") {
      lines.push(`  --color-${paletteName}: ${value};`);
    } else {
      for (const [shade, hex] of Object.entries(value)) {
        lines.push(`  --color-${paletteName}-${shade}: ${hex};`);
      }
    }
  }
  // Radius scale — Figma 라이브러리 동기화
  if (misc.radius?.scale) {
    lines.push("");
    lines.push("  /* Radius scale — synced from design-system/tokens/misc.json (Figma 라이브러리 truth) */");
    for (const [name, value] of Object.entries(misc.radius.scale)) {
      const px = typeof value === "number" ? `${value}px` : value;
      lines.push(`  --radius-${name}: ${px};`);
    }
  }
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

// ── Diff reporting ───────────────────────────────────────────────────────────

function printFirstDiffs(expected: string, actual: string, maxDiffs = 5): void {
  const expLines = expected.split("\n");
  const actLines = actual.split("\n");
  const total = Math.max(expLines.length, actLines.length);
  let found = 0;
  for (let i = 0; i < total && found < maxDiffs; i++) {
    if (expLines[i] !== actLines[i]) {
      console.error(`\n  Line ${i + 1}:`);
      console.error(`    - ${actLines[i] ?? "<missing>"}`);
      console.error(`    + ${expLines[i] ?? "<missing>"}`);
      found++;
    }
  }
  if (found === maxDiffs) {
    console.error(`\n  ... (showing first ${maxDiffs} differences)`);
  }
}

// ── Main ─────────────────────────────────────────────────────────────────────

function main(): void {
  const colors = JSON.parse(fs.readFileSync(COLORS_PATH, "utf-8")) as ColorsJson;
  const misc = JSON.parse(fs.readFileSync(MISC_PATH, "utf-8")) as MiscJson;
  const generated = generateCss(colors, misc);

  const isCheck = process.argv.includes("--check");

  if (isCheck) {
    let existing = "";
    try {
      existing = fs.readFileSync(OUTPUT_PATH, "utf-8");
    } catch {
      console.error("❌ tokens.generated.css is missing.");
      console.error(`   Expected: ${path.relative(ROOT, OUTPUT_PATH)}`);
      console.error("   Run: npm run sync-tokens");
      process.exit(1);
    }
    if (existing !== generated) {
      console.error("❌ tokens.generated.css is out of sync with design-system/tokens/");
      console.error(`   File: ${path.relative(ROOT, OUTPUT_PATH)}`);
      console.error("   Run: npm run sync-tokens");
      printFirstDiffs(generated, existing);
      process.exit(1);
    }
    console.log("✓ tokens.generated.css is in sync");
    return;
  }

  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, generated);
  console.log(`✓ Wrote ${path.relative(ROOT, OUTPUT_PATH)}`);
}

main();
